"""removed_can_create_hidden_from_user

Revision ID: 1a5ef8038b83
Revises: 3dd251a4de7e
Create Date: 2026-02-05 12:28:11.163815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1a5ef8038b83'
down_revision: Union[str, Sequence[str], None] = '3dd251a4de7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_roles', 'can_create_hidden')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_roles', sa.Column('can_create_hidden', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
