"""removed_s3_fields_from_bots

Revision ID: 3dd251a4de7e
Revises: 1faa8157204a
Create Date: 2026-02-05 12:07:51.350419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3dd251a4de7e'
down_revision: Union[str, Sequence[str], None] = '1faa8157204a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bots', 's3_auth_key')
    op.drop_column('bots', 's3_access_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('s3_access_key', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('bots', sa.Column('s3_auth_key', mysql.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###
