"""remove_taskex_createid

Revision ID: 6013750571f7
Revises: 3d3fe4933256
Create Date: 2026-02-05 23:01:40.083294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6013750571f7'
down_revision: Union[str, Sequence[str], None] = '3d3fe4933256'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_executions', 'status',
               existing_type=mysql.ENUM('BROADCASTED', 'CLAIMED', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'TIMEDOUT'),
               type_=sa.Enum('PENDING', 'BROADCASTED', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'TIMEDOUT', name='taskstatusenum'),
               existing_nullable=True)
    op.drop_constraint(op.f('task_executions_ibfk_2'), 'task_executions', type_='foreignkey')
    op.drop_column('task_executions', 'created_by_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_executions', sa.Column('created_by_id', mysql.VARCHAR(length=36), nullable=False))
    op.create_foreign_key(op.f('task_executions_ibfk_2'), 'task_executions', 'users', ['created_by_id'], ['user_id'])
    op.alter_column('task_executions', 'status',
               existing_type=sa.Enum('PENDING', 'BROADCASTED', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'TIMEDOUT', name='taskstatusenum'),
               type_=mysql.ENUM('BROADCASTED', 'CLAIMED', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'TIMEDOUT'),
               existing_nullable=True)
    # ### end Alembic commands ###
