"""task_execution_fields

Revision ID: 737ac92b35b9
Revises: 9bd242c2e44f
Create Date: 2026-02-05 19:41:38.139635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '737ac92b35b9'
down_revision: Union[str, Sequence[str], None] = '9bd242c2e44f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_executions', sa.Column('submitted_at', sa.DateTime(), nullable=True))
    op.add_column('task_executions', sa.Column('queued_at', sa.DateTime(), nullable=True))
    op.add_column('task_executions', sa.Column('claimed_at', sa.DateTime(), nullable=True))
    op.drop_column('task_executions', 'started_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_executions', sa.Column('started_at', mysql.DATETIME(), nullable=True))
    op.drop_column('task_executions', 'claimed_at')
    op.drop_column('task_executions', 'queued_at')
    op.drop_column('task_executions', 'submitted_at')
    # ### end Alembic commands ###
