"""add_name_desc_to_tasks

Revision ID: 9bd242c2e44f
Revises: 1a5ef8038b83
Create Date: 2026-02-05 18:07:37.399206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bd242c2e44f'
down_revision: Union[str, Sequence[str], None] = '1a5ef8038b83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('tasks', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'description')
    op.drop_column('tasks', 'name')
    # ### end Alembic commands ###
